// Generated by CoffeeScript 1.3.3
var ball, coffee_draw, config;

config = {
  width: 1000,
  height: 500,
  eventType: null
};

ball = {
  newX: 0,
  newY: 0,
  x: config.width / 2,
  y: config.height / 2
};

coffee_draw = function(p) {
  p.setup = function() {
    return p.size(config.width, config.height);
  };
  return p.draw = function() {
    ball.x += ball.newX;
    ball.y += ball.newY;
    if (ball.x < 0) {
      ball.x = 0;
    }
    if (ball.x > config.width - 25) {
      ball.x = config.width - 25;
    }
    if (ball.y < 0) {
      ball.y = 0;
    }
    if (ball.y > config.height - 25) {
      ball.y = config.height - 25;
    }
    p.background(100);
    p.ellipseMode(p.CORNER);
    return p.ellipse(ball.x, ball.y, 25, 25);
  };
};

$(document).ready(function() {
  var canvas, processing;
  canvas = $('canvas')[0];
  processing = new Processing(canvas, coffee_draw);
  if (window.DeviceOrientationEvent) {
    window.addEventListener("deviceorientation", function(orientData) {
      ball.newX = orientData.gamma / 2;
      ball.newY = orientData.beta / 2;
      return config.eventType = 'orientation';
    }, true);
  }
  if (window.DeviceMotionEvent && !config.eventType) {
    return window.addEventListener("devicemotion", function(event) {
      ball.newX = event.accelerationIncludingGravity.x * (-3);
      ball.newY = event.accelerationIncludingGravity.y * 3;
      return config.eventType = 'motion';
    }, true);
  }
});
